[package]
name = "serial-settings"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-storage = "0.3"
miniconf = "0.9"
menu = "0.4"
cortex-m = "0.7"
heapless = "0.8"
postcard = "1"
embedded-io = "0.6"
serde = { version = "1", default-features=false }
