[package]
name = "dsp"
version = "0.1.0"
authors = ["Robert Jördens <rj@quartiq.de>"]
edition = "2018"

[dependencies]
libm = "0.2.1"
serde = { version = "1.0", features = ["derive"], default-features = false }
generic-array = "0.14"

[dependencies.miniconf]
git = "https://github.com/quartiq/miniconf.git"
branch = "rs/issue-21/terminal-array-elements"

[dev-dependencies]
# criterion = "0.3"
rand = "0.8"
ndarray = "0.14"

[[bench]]
name = "micro"
harness = false

# Note: Due to a dependency injection bug, criterion enables std-features for serde, which breaks
# testing. Patch serde to not use std dependencies.
[patch.crates-io]
serde = { version = "1.0", features = ["derive"], default-features = false }

[features]
nightly = []
