remote_theme: pmarsceill/just-the-docs
title: Stabilizer
description: "User Manual"
logo: "/assets/stabilizer-logo.png"

#url: "https://quartiq.de"
#baseurl: "/stabilizer"

exclude: ['README.md']

plugins:
  - jekyll-remote-theme

# Enable an auxilary link in top right with a new tab open
aux_links:
  "Stabilizer on Github":
    - "//github.com/quartiq/stabilizer"
aux_links_new_tab: true
