[book]
authors = ["Ryan Summers", "Robert Jördens"]
language = "en"
multilingual = false
src = "src"
title = "Stabilizer"

[build]
create-missing = false
build-dir = "stabilizer-manual"

[preprocessor.toc]
marker = "<-- TOC -->"
command = "mdbook-toc"
renderer = ["html"]

[output.html]
site-url = "/stabilizer"
git-repository-url = "https://github.com/quartiq/stabilizer"

[output.linkcheck]
