name: HITL

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  hitl:
    runs-on: ubuntu-latest
    environment: hitl
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_PAT }}
          event-type: stabilizer
          repository: quartiq/hitl
          client-payload: '{"github": ${{ toJson(github) }}}'
