name: HITL

on:
  workflow_dispatch:
  pull_request:
    branches: [ master ]

jobs:
  hitl:
    runs-on: ubuntu-latest
    environment: hitl
    steps:
      - uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.DISPATCH_PAT }}
          event-type: stabilizer
          repository: quartiq/hitl
          client-payload: '{"github": ${{ toJson(github) }}}'

    - uses: fountainhead/action-wait-for-check@v1.0.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: HITL
        ref: ${{ github.event.pull_request.head.sha }}
